### DISCUSSION TITLE
how to enable TLS

### DISCUSSION THREAD

**Discussion by nbari** [quickwit-oss/quickwit#5317] [General]
Hi, how could TLS be configured?  this is my current working configuration but I would like to enable/add my certs (private CA):

```yaml
---
version: 0.8
node_id: node-1
listen_address: 0.0.0.0
metastore_uri: postgres://user:pass@host/quickwit

metastore:
  postgres:
    min_connections: 0
    max_connections: 10
    acquire_connection_timeout: 10s
    idle_connection_timeout: 10min
    max_connection_lifetime: 30min


indexer:
  enable_otlp_endpoint: true

jaeger:
  enable_endpoint: true
```
