### DISCUSSION TITLE
Generating snippet_fields when mode is dynamic

### DISCUSSION THREAD

**Discussion by jptmoore** [quickwit-oss/quickwit#5640] [Q&A]
Hi, I am struggling to get snippet_fields working for a schema such as:

```
version: "0.8"

doc_mapping:
  mode: dynamic
  dynamic_mapping:
    indexed: true
    stored: true
    tokenizer: default
    record: position
    expand_dots: true
    fast: true
```

My JSON data has a property called 'body' which could be an object containing 'value' e.g { "value": "foo" } or could also be within in an array e.g [{ "value": "foo" }] and I would like to generate snippets for "value". 

If I do something like:

`http 'http://localhost:7280/api/v1/foobar/search' query='body.value:foo' snippet_fields='body.value'
`

It generates a 500 response:

`{ "message": "internal error: `The field does not exist: 'body.value'`"}
`

I am not sure how to handle this within the dynamic schema.

Thanks.
