### DISCUSSION TITLE
Unable to Perform Full-Text Search on Fields Indexed via dynamic_mapping in Quickwit

### DISCUSSION THREAD

**Discussion by systemslife** [quickwit-oss/quickwit#5673] [Q&A] [answered]
I can perform full-text searches on fields indexed via `field_mappings` in Quickwit, but I am unable to search on fields indexed through `dynamic_mapping`. For example, with the schema below, I can search directly on fields like `levelname` or `trace_id`, but I cannot search on `plan_name` because it is indexed through `dynamic_mapping`.

**Example query:**
- `query=ERROR`: This search returns the document successfully.
- `query=basic`: This search does not return any results because `plan_name` is indexed using `dynamic_mapping`.

How can I perform a search on fields indexed through `dynamic_mapping` (like `plan_name`) in the same way as `field_mappings`?

## Example Schema:
```json
{
  "@timestamp": "2025-02-09T10:25:34.745128Z",
  "plan_name": "basic", 
  "levelname": "DEBUG", 
  "message": "[ERROR]",
  "time": "2025-02-09T10:25:34.744697Z",
  "trace_id": "b5ab2adc-e8c2-41de-bce6-069b734b66b1"
}
```

## Indexing Configuration:
```yaml
version: 0.7

index_id: app-logs

doc_mapping:
  mode: dynamic
  dynamic_mapping:
    indexed: true
    tokenizer: default
    record: position
    stored: true
  field_mappings:
    - name: "@timestamp"
      type: datetime
      input_formats:
        - "%Y-%m-%dT%H:%M:%S.%fZ"
      fast: true
    - name: levelname
      type: text
      tokenizer: raw
    - name: trace_id
      type: text
      tokenizer: raw
    - name: message
      type: text
      tokenizer: default
      record: position
      stored: true
  timestamp_field: "@timestamp"
  store_source: true

indexing_settings:
  commit_timeout_secs: 10

search_settings:
  default_search_fields: ["message"]

```
