### ISSUE TITLE
source from clickhouse

### ISSUE THREAD

**Issue by yangjinming1062** [quickwit-oss/quickwit#1298]
## Problem
I'm very interested in full-text search on ClickHouse , but I don't know how to use the data in ClickHouse as a source when writing the index. After searching the docs to no clickhouse as a metasource I checked the source code and found that there are only kafka_source file_source and push_api_source.
## Describe
Source configuration support ClickHouse.
## Additional context:
maybe the Source configuration will like this
```
# Sources
sources:
  - source_id: my-source-id
    source_type: clickhouse
    params:
      host: 127.0.0.1
      port: 9000
      user: ****
      password: ******
      databse: xxxx
```
