### ISSUE TITLE
The command query result does not match the API query

### ISSUE THREAD

**Issue by yangjinming1062** [quickwit-oss/quickwit#1318]
## Describe 
I execute the same query, the number of matches from the command line is correct, but the API's are less than the truth。

## Steps to reproduce the behavior:
1.  Query something with bash
```
./quickwit index search --index demo --query QueryTarget --config ./config/quickwit.yaml
```
2. Query same thing with REST
```
curl http://127.0.0.1:7280/api/v1/demo/search?query=QueryTarget
```
3. see the resulkt
## Demo
```

jinming.yang@qingteng:~/transfer/quickwit-v0.2.1$ ./quickwit index search --index demo --query 不可能存在的杨金明 --config ./config/quickwit.yaml
{
  "numHits": 3,
  "hits": [
    {
      "content": [
        "不可能存在的杨金明"
      ],
      "id": [
        "501612dd-6c8c-4683-8001-1d38a120e743"
      ]
    },
    {
      "content": [
        "不可能存在的杨金明"
      ],
      "id": [
        "501612dd-6c8c-4683-8001-1d38a120e743"
      ]
    },
    {
      "content": [
        "不可能存在的杨金明"
      ],
      "id": [
        "501612dd-6c8c-4683-8001-1d38a120e744"
      ]
    }
  ],
  "elapsedTimeMicros": 458823,
  "errors": []
}
jinming.yang@qingteng:~/transfer/quickwit-v0.2.1$ curl http://10.106.108.211:7280/api/v1/demo/search?query=%E4%B8%8D%E5%8F%AF%E8%83%BD%E5%AD%98%E5%9C%A8%E7%9A%84%E6%9D%A8%E9%87%91%E6%98%8E{
  "numHits": 1,
  "hits": [
    {
      "content": [
        "不可能存在的杨金明"
      ],
      "id": [
        "501612dd-6c8c-4683-8001-1d38a120e743"
      ]
    }
  ],
  "elapsedTimeMicros": 4723,
  "errors": []
}jinming.yang@qingteng:~/transfer/quickwit-v0.2.1$

```

## Configuration
version: quickwit-0.2.1
index:
```
version: 0 # File format version.

index_id: "demo"

doc_mapping:
  field_mappings:
    - name: id
      type: text
      indexed: false
      fast: false
    - name: content
      type: text
      stored: true
      tokenizer: default
      record: position
search_settings:
  default_search_fields: [content]

sources:
 - source_id: source-kafka
   source_type: kafka
   params:
     topic: yjm
     client_params:
       bootstrap.servers: 127.0.0.1:9092
       group.id: kafka-quickwit
       security.protocol: PLAINTEXT
```
