### ISSUE TITLE
Sort out what should be done for fields with a "." 

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#1334]
Right now we accepts fields with a dot in its name, but quickwti's behavior is then ill-defined.
In particular it interfers with the concept of object fields, json fields, and dynamic fields.

... We need some spec!

**Comment by fulmicoton** [comment]
# The problem

There are a bunch actors here:
- the quickwit schema:
	a) in the quickwit schema users can define field names including a ".".
	b) we support this to be friendly with legacy logs.
- the tantivy schema:
	We need to map these fields as tantivy fields, which in turns have field names.
- the query parser language:
	The query parser makes it possible to target a specific field.
	The query syntax goes `identity.username:fulmicoton`.
- the default fields, and in particular the dynamic field.
	Users can define a list of default fields in which the query will be searched. If no field is defined in the query, then things are easy: the default fields are search. If the query targets a specific existing field `body:toto` then that field will be targeted.

We need all of these actors to coexist in a natural, if not simple set rule.


# Solution

- Tantivy schema:

In the tantivy schema, field names with a "." see their "." escaped by a backslack.
e.g. `name=log.severity` translates into a tantivy field named `name=log\.severity`.
The point is not just to solve the improbable collision. It is also to make it possible to read the tantivy schema and get an idea of what was the original quickwit schema.
`\` is not allow in quickwit, so we do have a bijection here.

- Query parsing.

Upon query parsing a termquery with a define fieldname, the list of fields are acting like a routing system.

For instance, a field declared in the schema should act as follows:
- if it is not a JSON field, match `path_to_field`
- if it is JSON field, match `path_to_field([\.].+)*`
- if a `field_name` contains a '.' it gets a route both with the `\`. If there are no collision, it also gets a route with the `\`.

We need to cover the following unit tests:

```
field_mappings:
  - type: object # Field A
    name: identity
    field_mappings:
  	  - type: string
  	    name: username
  - type: string # Field B
    name: identity.username
```

`identity.username:fulmicoton` should target field A
`identity\.username:fulmicoton` should target field B

```
field_mappings:
	- type: string # Field B
  	  name: identity.username
```

`identity.username:fulmicoton` should target field B

The default fields with a json field should then only be matched if no other fields matched.

```
field_mappings:
	- type: string
  	  name: username
mode: dynamic
```

`username.toto:toto` should target the dynamic field or return an error.

```
field_mappings:
  - type: object # Field A
    name: identity
    field_mappings:
  	  - type: string
  	    name: username
mode: dynamic
```

`identity.username:toto` should target Field A.
`identity.address:` should target the dynamic field.



```
field_mappings:
  - type: json
    name: details
mode: dynamic
default_fields: 
	- details
```

`identity.username:toto` should target both the dynamic field and details.
