### ISSUE TITLE
Stricter checks on search (!?)

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#1373]
Quickwit accepted an corrupted config, and managed to index wth it, but emitted an error upon search.
This seems similar  to #1368 .

```
Command failed: Internal error: `Failed to deserialize index metadata: `unknown field `fieldnorms`, expected one of `name`, `type`, `stored`, `fast`, `indexed`, `tokenizer`, `record`, `field_mappings```.
````

The config:

```

version: 0

index_id:  hackernews_5

doc_mapping:
  store_source: false
  field_mappings:
    - name: id
      type: u64
      fast: true
    - name: type
      type: text
      tokenizer: raw
    - name: by
      type: text
      tokenizer: default
      record: position
    - name: text
      type: text
      record: position
      tokenizer: raw
    - name: url
      type: text
      tokenizer: default
      record: position
    - name: title
      type: text
      tokenizer: default
      record: position

search_settings:
  default_search_fields: [title,by,text]

```
