### ISSUE TITLE
UI does not show docs inline on a full dynamic index.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#1490]
To reproduce create an index with a dynamic index and no field.

The unfolded UI works, but the inline docs are blank.

**Comment by fulmicoton** [comment]
![screenshotlog](https://user-images.githubusercontent.com/1021506/169181857-3f1c1dc7-f834-4aef-872a-00e61c8ae93a.png)

**Comment by fmassot** [comment]
can you share your index config?

**Comment by fulmicoton** [comment]
Full dynamic

```yaml
version: 0
index_id: wikijson
doc_mapping:
  mode: dynamic
```
