### ISSUE TITLE
Can't use a key as default search field for JSON field

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#1503]
Occurred as I was writing the Kafka tutorial. On main branch.

```yaml
...
doc_mapping:
  field_mappings:
    - name: org
      type: json
      tokenizer: default
...
search_settings:
  default_search_fields: [org.name]
```

```bash
quickwit index create --index-config ...
Command failed: Unknown default search field: `org.name`
````

**Comment by fmassot** [comment]
Fixed in 0.6.

**Comment by mvrhov** [comment]
This one seems to have resurfaced. I'm trying to setup a json field to be a default one, so one doesn't need to prefix when searching into the json. Quickwit v0.8.2

```
...
doc_mapping:
  field_mappings:
... other field mappings.
    - name: org
      type: json
      tokenizer: raw
...
```
search_settings:
  default_search_fields: [org]

**Comment by fmassot** [comment]
@mvrhov what is your expected behavior in this case? If it's a json field, I would expect default search fields like `org.id` or `org.name`...

**Comment by trinity-1686a** [comment]
If I understand correctly, I don't think it's a good idea. My understanding is you want `abc:def` to match documents the same way as `org.abc:def` when `org` is a default field (correct me if I'm wrong)

assuming the following doc mapping
```yaml
# a few things are left out
doc_mapping:
  field_mappings:
    - name: id
        type: text
        tokenizer: raw
    - name: org
      type: json
      tokenizer: raw

search_settings:
  default_search_fields: [org]
```
and a doc
```json5
{
  "id": "my_id",
  "org": {
    "id": "org_id",
    "foo": "foo",
    "org": {
      "id": "org_org_id",
      "bar": "bar"
    }
  }
}
```

Should `id:xyz` search in only in `id` or in `org.id` too? If it searches in both, you can't search for just `id` anymore, but if it doesn't search in `org.id`, the behavior differs from searching for `foo:xyz` which is confusing.
Should `org.id` search in `org.id` or in `org.org.id` (or in both), not even knowing in advance if these fields might exist or not (in this case they both do)?

While I see the convenience it brings, I strongly believe using default_search_field as a prefix for fields explicitly provided in request will lead to more confusion, and in the end, something that's generally harder to use correctly.
