### ISSUE TITLE
run service indexer in 0.3.0 

### ISSUE THREAD

**Issue by chenjinlei1122** [quickwit-oss/quickwit#1656]
**Is your feature request related to a problem? Please describe.**
run a  indexer service 
in version 0.2.1, use command
`service run indexer --indexes trace`
in version 0.3.0,  use command
`run --service indexer --indexes  trace`
it not run and error
` error: Found argument '--indexes' which wasn't expected, or isn't valid in this context
        If you tried to supply `--indexes` as a value rather than a flag, use `-- --indexes` `
 
I don't know what causes, the documentation don't have example command
![image](https://user-images.githubusercontent.com/32697166/174794719-bbbfcbe9-f54a-422c-9333-0ab6fee039a1.png)

**Additional context**
index yaml
```
version: 0 # File format version.

index_id: trace

doc_mapping:
    field_mappings:
        - name: id
          type: u64
          fast: true
        - name: raw_content
          type: text
          tokenizer: default
          record: position
search_settings:
    default_search_fields: [raw_content]

sources:
    - source_id: source-kafka
      source_type: kafka
      params:
          topic: UserAction
          client_params:
              bootstrap.servers: 127.0.0.1:9092
              group.id: FullText
              security.protocol: PLAINTEXT
```
@fulmicoton need your help

**Comment by fulmicoton** [comment]
@chenjinlei1122 we deprecated this option. Today it is not possible to select a subset of index. All indexing pipeline are started automatically.

We have a 0.3.1 released scheduled rapidly. Is this something you need?

**Comment by chenjinlei1122** [comment]
@fulmicoton  
0.2.1 docker-compose.yaml
```
services:
    quickwit_init:
        image: quickwit:quickwit:latest
        container_name: quickwit_init
        command: index create --index-config /quickwit/config/trace.yaml
        volumes:
            - /opt/quickwit:/quickwit/qwdata

    quickwit_indexer:
        restart: always
        image: quickwit:quickwit:latest
        command: service run indexer --indexes traceback
        volumes:
            - /opt/quickwit:/quickwit/qwdata
        depends_on:
            - quickwit_init

    quickwit_searcher:
        restart: always
        image: quickwit:quickwit:latest
        command: service run searcher
        volumes:
            - /opt/quickwit:/quickwit/qwdata
        ports:
            - "7280:7280"
        depends_on:
            - quickwit_indexer
```
0.3.0 it's only need create index, then run --service searcher, don't need run --service indexer ?

**Comment by fulmicoton** [comment]
```
services:
    quickwit_init:
        image: quickwit:quickwit:latest
        container_name: quickwit_init
        command: index create --index-config /quickwit/config/trace.yaml
        volumes:
            - /opt/quickwit:/quickwit/qwdata

    quickwit_indexer:
        restart: always
        image: quickwit:quickwit:latest
        command: run --service indexer # <----------------- changed
        volumes:
            - /opt/quickwit:/quickwit/qwdata
        depends_on:
            - quickwit_init

    quickwit_searcher:
        restart: always
        image: quickwit:quickwit:latest
        command: run --service searcher    # <----------------- changed
        volumes:
            - /opt/quickwit:/quickwit/qwdata
        ports:
            - "7280:7280"
        depends_on:
            - quickwit_indexer
```
