### ISSUE TITLE
Problem with Scaleway's S3 compatible Object Storage

### ISSUE THREAD

**Issue by demangejeremy** [quickwit-oss/quickwit#1897]
Scaleway has a cheap formula for S3 storage. This makes it perfect for QuickWit. Only, I've been stuck running Scaleway's Object Storage from QuickWit for two days now. Has anyone succeeded?

**Describe the bug**

I used the latest published version of DockerHub : quickwit/quickwit:edge. I also tried to make it work without Docker since version 0.3.1, tested by building a new version for Ubuntu from the master and nothing helps. I get this error here:

```
Caused by:
    Internal error: `Failed to put {INDEXES_STATES_FILENAME} file.` Cause: `StorageError(kind=Unauthorized, source=Request ID: None Body: <?xml version='1.0' encoding='UTF-8'?>
    <Error><Code>AccessDenied</Code><Message>Access Denied.</Message><RequestId>***-***</RequestId></Error>)`.
```

**Steps to reproduce**

1. Prepare env file:

```
AWS_ACCESS_KEY_ID=***
AWS_SECRET_ACCESS_KEY=***
AWS_DEFAULT_REGION=fr-par
AWS_REGION=fr-par
QW_S3_ENDPOINT=https://***.s3.fr-par.scw.cloud
```

2. Prepare config.yaml:

```yaml
version: 0
node_id: searcher-1
listen_address: 0.0.0.0
metastore_uri: s3://***.s3.fr-par.scw.cloud/indexes
default_index_root_uri: s3://***.s3.fr-par.scw.cloud/indexes
```

3. Run this command:

`docker run -v "$(pwd)":"/quickwit/qwdata" --env-file .env quickwit/quickwit:edge index create --index-config ./qwdata/hdfs_logs_index_config.yaml --config ./qwdata/config.yaml`

**Expected behavior**

That it adds something to my S3 at least 😭 
All my Scaleway tokens are correct after checks, so I don't understand at all where the problem occurs.

**Configuration:**

Docker with `quickwit/quickwit:edge`.

1. Output of `quickwit --version`: `0.3.1-nightly`
