### ISSUE TITLE
Whether there is an automatic stop mechanism for indexer

### ISSUE THREAD

**Issue by yangjinming1062** [quickwit-oss/quickwit#1922]
**Describe the bug**
I have a index called Demo, and this is the indexer cmd: quickwit service run indexer --indexes Demo.
I run the indexer by supervisord. I wish it to run forever, but sometimes I find that indexer has stopped working.

**Expected behavior**
I would like to know the cause of this problem and how to avoid it.

**Configuration:**
Please provide:

1. quickwit --version: 0.2.1
2. The index_config.yaml
```
---
version: 0 # File format version.

index_id: Demo

doc_mapping:
    field_mappings:
        - name: id
          type: u64
          fast: true
        - name: raw_content
          type: text
          tokenizer: default
          record: position
search_settings:
    default_search_fields: [raw_content]

sources:
    - source_id: source-kafka
      source_type: kafka
      params:
          topic: UserAction
          client_params:
              bootstrap.servers: $(KAFKA)
              group.id: FullText
              security.protocol: PLAINTEXT
```
3. The quickwit.yaml
```
# ============================ Quickwit Configuration ==============================

version: 0

listen_address: 0.0.0.0
rest_listen_port: 7280

metastore_uri: file://./qwdata/indices#polling_interval=30s
```
