### ISSUE TITLE
Performance regression of ingestion throughput with commit bc67a5a

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#2074]
PR from which I saw a division by 4 or 5 of the ingestion throughput: https://github.com/quickwit-oss/quickwit/commit/bc67a5a1c02b367ac3056b97843148eae281ad00

The doc mapping timestamp field is:

```yaml
    - name: timestamp
      type: datetime
      input_formats:
        - unix_ts_millis
      precision: "milliseconds"
```
