### ISSUE TITLE
janitor supports incremental execution

### ISSUE THREAD

**Issue by guidao** [quickwit-oss/quickwit#2094]
During our usage we found that postgres has a lot of Lock state transactions. This caused the pipeline to restart due to fetching connection timeouts.
When I stopped the janitor execution, I noticed that there were a lot less transactions waiting. This might have something to do with the fact that janitor is getting a lot of splits, so maybe it could be executed in batches, with a fixed number of splits at a time.

<img width="1345" alt="image" src="https://user-images.githubusercontent.com/3192136/195273869-db09d0ec-b2a5-4943-9948-c9a12dbc0063.png">

**Comment by guidao** [comment]
index config:
```yaml
version: 0

index_id: logs

indexing_settings:
  timestamp_field: unix_ms

search_settings:
  default_search_fields: [log]

sources:
  - source_id: kafka
    source_type: kafka
    num_pipelines: 3
    params:
      topic: log.log-container.stdout
      client_log_level: debug
      client_params:
        bootstrap.servers: '${ip}'
        group.id: quickwit
        debug: all
        log_level: 7
        auto.offset.reset: latest

doc_mapping:
  partition_key: app_name
  max_num_partitions: 50
  tag_fields: [app_name]
  field_mappings:
    - name: app_name
      type: text
      tokenizer: raw
      fast: true
    - name: unit_name
      type: text
      tokenizer: raw
      fast: true
    - name: version
      type: text
      tokenizer: raw
      fast: true
    - name: idc
      type: text
      tokenizer: raw
      fast: true
    - name: container_name
      type: text
      tokenizer: raw
      fast: true
    - name: pod
      type: text
      tokenizer: raw
      fast: true
    - name: log
      type: text
    - name: unix_ms
      type: i64
      fast: true

```
