### ISSUE TITLE
The `ingest` CLI command does not merge splits

### ISSUE THREAD

**Issue by ChillFish8** [quickwit-oss/quickwit#2308]
When creating a set of splits with the following index config (index_uri omitted) we see no merges being attempted by Quickwit while indexing documents via the `ingest` command.

We can observe the merge pipeline being started in the logs:
```
2022-11-14T15:09:57.681Z  INFO spawn_pipeline{^[[3mindex^[[0m^[[2m=^[[0mtest-index ^[[3mgen^[[0m^[[2m=^[[0m0}: quickwit_indexing::actors::indexing_pipeline: Spawning indexing pipeline. index_id=test-index source_id=_cli-ingest-source pipeline_ord=0 root_dir=/home/chillf>
```

And then see it very shortly after being killed with the following log:
```
2022-11-14T15:10:00.602Z  INFO quickwit_indexing::actors::indexing_service: No more indexing pipeline on this index and source, killing merge pipeline. index_id=test-index source_id=_cli-ingest-source
```

This does not get restarted and leaves us with hundreds of thousands of small splits that need to be merged.

#### Index Config
```yaml
version: 0

index_id: "test-index"

doc_mapping:
  mode: lenient
  field_mappings:
    - name: user
      type: text
      tokenizer: raw
    - name: item
      type: text
      tokenizer: raw
    - name: rating
      type: f64
      fast: true
    - name: timestamp
      type: i64
      fast: true

  partition_key: user
  max_num_partitions: 100

indexing_settings:
  timestamp_field: timestamp
  commit_timeout_secs: 1

  resources:
    num_threads: 1


search_settings:
  default_search_fields: [user, item]
```
