### ISSUE TITLE
Failed to parse index_config

### ISSUE THREAD

**Issue by yangjinming1062** [quickwit-oss/quickwit#2407]
**Describe the bug**
I used the 0 as version in the index_config.yaml just like quickstart, but I found  error when I create index.
![image](https://user-images.githubusercontent.com/30614179/203895259-1630ad73-e315-4dda-96f4-3f28e3f9d0cc.png)
![image](https://user-images.githubusercontent.com/30614179/203896048-dd0ef02d-4b75-4216-a0f9-56c89f786743.png)

**Configuration:**
Please provide:

1. quickwit --version:0.3.1-nightly
2. The index_config.yaml
```
---
version: 0 # File format version.

index_id: traceback

doc_mapping:
    field_mappings:
        - name: id
          type: u64
          fast: true
        - name: raw_content
          type: text
          tokenizer: default
          record: position
search_settings:
    default_search_fields: [raw_content]

sources:
    - source_id: source-kafka
      source_type: kafka
      params:
          topic: UserAction
          client_params:
              bootstrap.servers: 127.0.0.1
              group.id: FullText
              security.protocol: PLAINTEXT

```
