### ISSUE TITLE
 full-text search with clickhouse

### ISSUE THREAD

**Issue by qiyuxin** [quickwit-oss/quickwit#2619]
When combined with CK, from the relevant guidance documents, does it need data to be stored in CK and Quickwit at the same time to achieve fast full-text search? For local testing, the data is only stored in CK, and cannot be queried through the API interface provided by QuickWit

**Comment by fulmicoton** [comment]
The documents do not need to be marked as STORED in quickwit's index. The join key needs to be marked as a fast field however... and the field that are meant to be searched have to be  INDEXED

**Comment by qiyuxin** [comment]
Follow this guide for local testing, but gh-archive-2021-12.json.gz is not stored in Quickwit, and the test result is that the data cannot be returned through the API query (like this SELECT count(*)
FROM url('http://127.0.0.1:7280/api/v1/gh-archive/search/stream?query=clickhouse&fastField=id&outputFormat=clickHouseRowBinary', RowBinary, 'id UInt64')), so which step went wrong?

> The documents do not need to be marked as STORED in quickwit's index. The join key needs to be marked as a fast field however... and the field that are meant to be searched have to be INDEXED

**Comment by fulmicoton** [comment]
You do need to index the data in quickwit at one point.

Have you stricly followed the isntructions?
https://quickwit.io/docs/tutorials/add-full-text-search-to-your-olap-db/

**Comment by fmassot** [comment]
In the tutorial, this command line is indexing docs: `./quickwit index ingest --index gh-archive`

**Comment by qiyuxin** [comment]
./quickwit index ingest --index gh-archive  
Does this command store the index of the data to be queried in the total data stored in ck in quickwit?

> In the tutorial, this command line is indexing docs: `./quickwit index ingest --index gh-archive`

**Comment by fmassot** [comment]
> Does this command store the index of the data to be queried in the total data stored in ck in quickwit?

This command generates an index of the dataset; if you do it locally, you will find the index files (called splits) in `qwdata/indexes/gh-archive`. 
To know what is inside a split (= a piece of the index), you have to look at the doc mapping, which defines what you want to store in the index. Basically, you can define what you will store for each field in your document: the raw data (docstore), the indexed data (inverted index), and the fast field (columnar storage).

**Comment by qiyuxin** [comment]
In the tutorial:
1 gunzip -c gh-archive-2021-12-text-only.json.gz | ./quickwit index ingest --index gh-archive，This command generates an index of the dataset；
2 gunzip -c gh-archive-2021-12.json.gz | clickhouse-client -d gh-archive --query="INSERT INTO github_events FORMAT JSONEachRow" ，this  command  insert data into ClickHouse; 

Is it necessary to complete the above two steps to query ck data through quickwit? If so, for the data already in ck, it is necessary to create a index file similar to gh-archive-2021-12-text-only.js.gz and import it to quickwit first. And then you can query it, right?


> 
> This command generates an index of the dataset; if you do it locally, you will find the index files (called splits) in `qwdata/indexes/gh-archive`. To know what is inside a split (= a piece of the index), you have to look at the doc mapping, which defines what you want to store in the index. Basically, you can define what you will store for each field in your document: the raw data (docstore), the indexed data (inverted index), and the fast field (columnar storage).

**Comment by fmassot** [comment]
> s it necessary to complete the above two steps to query ck data through quickwit? If so, for the data already in ck, it is necessary to create a index file similar to gh-archive-2021-12-text-only.js.gz and import it to quickwit first. And then you can query it, right?

Yes, you need to index the data both in quickwit and clickhouse.

But you can limit the data you put in Quickwit to the minimum like this:

```yaml

version: 0.4
index_id: gh-archive
# By default, the index will be stored in your data directory,
# but you can store it on s3 or on a custom path as follows:
# index_uri: s3://my-bucket/gh-archive
# index_uri: file://my-big-ssd-harddrive/
doc_mapping:
  store_source: false
  field_mappings:
    - name: id
      type: u64
      fast: true
      stored: false
    - name: created_at
      type: datetime
      input_formats:
        - unix_timestamp
      output_format: unix_timestamp_secs
      precision: seconds
      fast: true
      stored: false
    - name: title
      type: text
      tokenizer: default
      record: position
      stored: false
    - name: body
      type: text
      tokenizer: default
      record: position
      stored: false
  timestamp_field: created_at

search_settings:
  default_search_fields: [title, body]

```


You will notice that I put all fields with `stored: false`. This means we will only have the inverted indexes in quickwit + fast column storage on the `id` and `created_at`.
