### ISSUE TITLE
Support for regex tokenizer

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#2652]
A regex tokenizer is now available in tantivy.

```yaml
field_mappings:
  - name: message
    type: text
    tokenizer: regex # or "pattern" à la ES?
    pattern: \W+
```
