### ISSUE TITLE
Check  pulsar authentification yaml deserialization and fix?

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#2899]
It's impossible to define Pulsar authentication parameters in YAML though it works in JSON.

In JSON:

```json
{
    "topics": ["my-topic"],
    "address": "pulsar://localhost:6560",
    "consumer_name": "my-pulsar-consumer",
    "authentication": {
        "token":"my-token"
    }
}
```

YAML config not working

```yaml
topics:
- my-topic
address: pulsar://localhost:6560
consumer_name: my-pulsar-consumer
authentication:
  token: my-token
```
