### ISSUE TITLE
Support for S3's Virtual-hosted–style access

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#3080]
As described here.
https://docs.amazonaws.cn/en_us/AmazonS3/latest/userguide/access-bucket-intro.html

We need to chekc if it works today and support it/document if it doesn't

**Comment by guilload** [comment]
Closed via #3446 and #3467.

Virtual-hosted–style access is now the default. It can be disabled with `QW_S3_FORCE_PATH_STYLE_ACCESS` or:

```yaml
# node config

storage:
  s3:
    force_path_style_access: true
```
