### ISSUE TITLE
Support specifying a timezone manually with strptime parser

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#3171]
For instance:
```yaml
name: timestamp
type: datetime
description: Time at which the event was emitted
input_formats:
  - rfc3339
  - unix_timestamp
  - "%Y %m %d %H:%M:%S.%f %z"
  - strptime:
    format: "%Y %m %d %H:%M:%S.%f"
    timezone: America/New_York
```
