### ISSUE TITLE
Ingest endpoint doesn't report document errors.

### ISSUE THREAD

**Issue by ph** [quickwit-oss/quickwit#3190]
**Describe the bug**

When using the ingest endpoint to index a `json` formatted body and there is an error in one of the document, the error will not be reported to the user.

**Steps to reproduce**

1. Use the following mapping:
```yaml
version: 0.5
index_id: friends
doc_mapping:
  mode: "lenient"
  field_mappings:
    - name: name
      type: text
    - name: points
      type: i64
      fast: true
    - name: last_modified_at
      type: datetime
      fast: true
indexing_settings:
    commit_timeout_secs: 1

```
3. Insert a set of documents with an invalid document see the `PH` entry with a `last_modified_at` date set to February **31**.
```sh
curl -XPOST "http://ogdru-jahad.local:7280/api/v1/friends/ingest" -H 'Content-Type: application/json' -d '{ "id": 1, "name": "Bernard", "points": 10, "last_modified_at": "2023-04-17T20:40:00Z" }
{ "id": 2, "name": "Alice", "points" :  20, "last_modified_at": "2023-01-01T12:00:00Z" }
{ "id": 3, "name": "Caroline", "points": 50, "last_modified_at": "2023-04-18T13:00:00Z" }
{ "id": 4, "name": "PH", "points": 5, "last_modified_at": "2023-02-31T00:00:00Z" }
{ "id": 5, "name": "Bob", "points": 42, "last_modified_at": "2023-01-28T03:00:00Z" }'
```

The API response:

```json
{
  "num_docs_for_processing": 5
}
```

But only 4 documents will be indexed and I do not see anything in the log but I am running at `INFO` level.

**Expected behavior**
I would expect to see some kind of parsing error returned to the user.

**Configuration:**
Please provide:

1. Output of `quickwit --version`
 Quickwit 0.5 (docker image)
