### ISSUE TITLE
aggregation does not work on inner field

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#3224]
It is not possible to run an aggregation on `actor.login` on gharchive with 
` - name: actor.login
    type: text
    fast: true`
in the docmapper

The cause is not identified yet.

**Comment by fulmicoton** [comment]
The following however works:
```
version: 0.5
index_id: gharchive
doc_mapping:
  mode: lenient
  field_mappings:
    - name: type
      type: text
      fast: true
    - name: actor
      type: object
      field_mappings:
        - name: login
          type: text
          fast: true
```
