### ISSUE TITLE
CLI `quickwit index delete` command: Index deletion always happens even when asking to not delete the index

### ISSUE THREAD

**Issue by karuppiah7890** [quickwit-oss/quickwit#3378]
**Describe the bug**

When I invoke `quickwit index delete` command to delete an index but say `n` (for `no`) to abort (or `Ctrl + C` or `Enter` to choose the default `no`), it still goes ahead and deletes the index 😅 It even deletes the index before I even respond to the `Do you want to proceed?` question

**Steps to reproduce (if applicable)**
Steps to reproduce the behaviour:

1.  Have an index config yaml file. `curl -o hdfs_logs_index_config.yaml https://raw.githubusercontent.com/quickwit-oss/quickwit/main/config/tutorials/hdfs-logs/index-config.yaml`
2. Create an index with the index yaml config file. `quickwit index create --index-config hdfs_logs_index_config.yaml`
3. List the indices / indexes using `quickwit index list`
4. Now invoke the delete command to delete the index. `quickwit index delete --index hdfs-logs`. Do not respond to the question `Do you want to proceed?`
5. Check the logs of server to see the index getting deleted. I think the log to look for is something like this - `2023-05-19T17:35:29.970Z  INFO quickwit_janitor::actors::delete_task_service: Remove deleted index from delete task pipelines. deleted_index_id="hdfs-logs"`, but I'm not sure

**Expected behavior**

I expected the index to Not get deleted if I said `n` (`no`) or `Ctrl + C` or `Enter` for default `no` option. I expected the command line to wait for my answer to the `Do you want to proceed?` question before proceeding ahead always and deleting the index 😅 

**Configuration:**
Please provide:

1. Output of `quickwit --version`

```
Quickwit v0.5.0 (d4be690 2023-03-17T09:18:41Z)
```

3. The index_config.yaml

```yaml
version: 0.5

index_id: hdfs-logs

doc_mapping:
  field_mappings:
    - name: timestamp
      type: datetime
      input_formats:
        - unix_timestamp
      output_format: unix_timestamp_secs
      precision: seconds
      fast: true
    - name: tenant_id
      type: u64
    - name: severity_text
      type: text
      tokenizer: raw
    - name: body
      type: text
      tokenizer: default
      record: position
    - name: resource
      type: json
      tokenizer: raw
  tag_fields: [tenant_id]
  timestamp_field: timestamp

search_settings:
  default_search_fields: [severity_text, body]
```
