### ISSUE TITLE
Support `partition_key` on key within json field or key with dots

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#3380]
Currently, it's not possible to define a partition key on
- a key in a JSON field
- a key that contains a dot (and probably containing special characters).

For example, if I create an index with a partition key on `span_attributes.tenant_id`, I get the following error:

```
Invalid config: Failed to interpret the partition key.: Parsing Error: ().
```

**Comment by jeromegn** [comment]
We'd be interested in using this.

I've had to remap some nested fields to be top level to make partitioning work.

**Comment by fulmicoton** [comment]
@jeromegn  Can you share the actual JSON? usually remapping is not necessary.

If your json looks like 
```json
{
    "my_obj": {
        "tenant_id" 33,
        "attribute1": "red",
        "attribute2": "red"
    }
}
```

We support declaring `my_obj.tenant_id` in your schema, and keeping the rest as dynamic.

**Comment by jeromegn** [comment]
I wasn't able to use a nested key for partitioning. I got the error described in the OP

**Comment by fulmicoton** [comment]
Understood!

**Comment by jeromegn** [comment]
Sorry, I wrote that as I was getting to bed with my brain fried.

The index looks like this:

```yaml
version: 0.6

index_id: app-logs

doc_mapping:
  field_mappings:
    - name: timestamp
      type: datetime
      precision: nanoseconds
      output_format: unix_timestamp_nanos
      fast: true
      
    - name: message
      type: text
      stored: true

    - name: fly
      type: object
      field_mappings:
      - name: org
        type: object
        field_mappings:
          - name: id
            type: u64
            fast: true
      - name: app
        type: object
        field_mappings:
          - name: id
            type: u64
            fast: true
          - name: name
            type: text
            tokenizer: raw
            fast: true
          - name: instance
            type: text
            tokenizer: raw
            fast: true
      - name: datacenter
        type: text
        tokenizer: raw
      - name: provider
        type: text
        tokenizer: raw
      - name: region
        type: text
        fast: true
        tokenizer: raw
    - name: host
      type: object
      field_mappings:
        - name: hostname
          type: text
          tokenizer: raw
    - name: event
      type: object
      field_mappings:
        - name: provider
          type: text
          tokenizer: raw
    - name: log
      type: object
      field_mappings:
        - name: level
          type: text
          tokenizer: raw

  tag_fields: []
  store_source: false
  timestamp_field: timestamp
  mode: dynamic
  partition_key: fly.org.id,fly.app.id

search_settings:
  default_search_fields: [message]

indexing_settings:
  commit_timeout_secs: 10
  split_num_docs_target: 10000000
  resources:
    heap_size: 2GB
```

This returns the same error as the original post.
