### ISSUE TITLE
Add an N-Gram tokenizer in Quickwit

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#3392]
Add an n-gram toknizer within quickwit. 

It is already present in tantivy.
We probably can have something that goes

We probably do not need to document its presence at the moment.

This tokenizer has parameters.
(min_ngram max_ngram and prefix only)

@drusellers which parameters would you want here?

**Comment by drusellers** [comment]
This is what I'm thinking:

A tri-gram configuration

```yaml
# elided

doc_mapping:
  field_mappings:
    - name: name
      type: text
      tokenizer: n_gram
      min_ngram: 3
      max_ngram: 3
      prefix_only: false
```

Then for an edge gram you could do


```yaml
# elided

doc_mapping:
  field_mappings:
    - name: name
      type: text
      tokenizer: n_gram
      min_ngram: 3
      max_ngram: 10
      prefix_only: true
```
