### ISSUE TITLE
When Metastore crashes, historical traces are no longer visible in Jaeger

### ISSUE THREAD

**Issue by Tyrion85** [quickwit-oss/quickwit#3442]
**Describe the bug**
This is regarding Quickwit as a storage for Jaeger traces and OTEL Collector.

Setup is in kubernetes, installed via helm chart. Metastore can sometimes get overwhelmed and crash, for example it can get OOMKilled. At that point, after Metastore recovers (more memory thrown at it), and when Indexer pod is manually restarted, all "previous" traces searched in Jaeger are lost. Data still exists in the bucket.

Not sure why this happens, or how to mitigate it. Is this an expected behaviour? A known issue? Is it a quirk of my setup? Although, I really don't have anything custom - just a bog standard installation of Quickwit via helm chart, OTEL Collector installed via helm chart, and Jaeger also installed via helm chart with pretty much defaults, except for connecting each other.

**Steps to reproduce (if applicable)**

1. Install Quickwit helm chart o k8s, install OTEL collector, install Jaeger
2. Use default values for Quickwit
3. Relevant OTEL Collector config:
```
    exporters:
      jaeger:
        endpoint: jaeger-collector:14250
        tls:
          insecure: true
      otlp/quickwit:
        endpoint: quickwit-indexer:7281
        tls:
          insecure: true
    service:
      extensions: [ health_check ]
      pipelines:
        traces:
          receivers: [ otlp,opencensus,zipkin,jaeger ]
          processors: [ batch ]
          exporters: [ jaeger,otlp/quickwit ]
```
4. Relevant Jaeger config:
```
storage:
    type: grpc-plugin
query:
    extraEnv:
    - name: GRPC_STORAGE_SERVER
      value: quickwit-searcher:7281
collector:
    extraEnv:
    - name: GRPC_STORAGE_SERVER
      value: quickwit-searcher:7281
```
5. Make sure there are some traces stored in a bucket (I use GCP). Make sure traces are searchable in Jaeger
6. Make sure metastore crashes. Recover it, and restart indexer (for some reason, in my setup it cannot recover on its own and needs manual intervention)
7. Search for "old" traces. In my case, they are no longer available, but data is still present in the bucket.

----
Some of the logs that can be observed:
- indexer:
```
[2m2023-05-30T10:10:20.995Z[0m [31mERROR[0m [2mquickwit_actors::spawn_builder[0m[2m:[0m actor-failure [3mcause[0m[2m=[0mFailed to receive command from uploader.


[31mERROR[0m [2mquickwit_actors::spawn_builder[0m[2m:[0m actor-failure [3mcause[0m[2m=[0mAn IO error occurred: 'Directory kill switch was activated.' [3mexit_status[0m[2m=[0mFailure(An IO error occurred: 'Directory kill switch was activated.')
```

Searcher:
```
[2m2023-05-30T10:10:40.700Z[0m [31mERROR[0m [1mget_services[0m[2m:[0m[1mroot_list_terms[0m[2m:[0m [2mquickwit_search::root[0m[2m:[0m Leaf search response contains at least one failed split. [3mfailed_splits[0m[2m=[0m[SplitSearchError { error: "Internal error: `Failed to fetch hotcache and footer from s3://quickwit/indexes/otel-trace-v0 for split `01H1EKCGK65MKBKXAD3NYBEVZ9``.", split_id: "01H1EKCGK65MKBKXAD3NYBEVZ9", retryable_error: true }]
```

**Expected behavior**
Metastore can crash from time to time, this is normal in cloud native world. Expected behaviour is for old traces to be searchable, as they were before the metastore crashed.

**Configuration:**
Given above

Quickwith helm chart **0.3.4**
Image: **quickwit/quickwit:v0.5.0** 
Let me know if I can provide any more detail here 🙏🏼
