### ISSUE TITLE
Ability to disable S3 multipart upload

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#3486]
For instance, it's not supported by GCS.

Opening for visibility, since we shouldn't be using this API at all with the current policy.

**Comment by guilload** [comment]
```yaml
storage:
  s3:
    disable_multipart_upload
```

Closed via #3591.
