### ISSUE TITLE
Search `field:number` on stackoverflow dataset returns no document with dynamic index config

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#3542]
Quickwit version: main branch

`answerId:"7"` or `answerId:7` queries do not return documents.

`type:answer` returns documents.

Here is the emitted tantivy query:

```
BooleanQuery { subqueries: [(Should, TermQuery(Term(field=3, type=Json, path=answerId, type=U64, 20431))), (Should, TermQuery(Term(field=3, type=Json, path=answerId, type=Str, "20431")))] }
```

I think we should emit `TermQuery(Term(field=3, type=Json, path=answerId, type=I64, 20431)`, not `U64`.

Index config used:

```yaml

version: 0.6

index_id: stackoverflow

doc_mapping:
  mode: dynamic
  field_mappings:
    - name: title
      type: text
      tokenizer: default
      record: position
      stored: true
    - name: body
      type: text
      tokenizer: default
      record: position
      stored: true
    - name: creationDate
      type: datetime
      fast: true
      input_formats:
        - rfc3339
      precision: seconds
  timestamp_field: creationDate

search_settings:
  default_search_fields: [title, body]

indexing_settings:
  commit_timeout_secs: 10

```
