### ISSUE TITLE
How much memory does the indexer requires

### ISSUE THREAD

**Issue by dojiong** [quickwit-oss/quickwit#3577]
quickwit's docment says [Indexer works with a default heap of 2 GiB of memory.](https://quickwit.io/docs/configuration/index-config#indexer-memory-usage)

I deployed a cluster via Helm with limit beblow, but one indexer node always trigger OOM
```yaml
resources:
  limits:
    cpu: "4"
    memory: 8Gi
  requests:
    cpu: "1"
    memory: 4Gi
```
