### ISSUE TITLE
Doc processing error with a json mapping and null value

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#3670]
While indexing GH archive dataset, I got this error:

```
2023-07-20T07:24:14.984Z  WARN quickwit_indexing::actors::doc_processor: error=ValueError("payload.pull_request.head.repo", "Expected an JSON Object, got null")
```

Here is the mapping:

```yaml
doc_mapping:
  field_mappings:
    - name: id
      type: text
    - name: type
      type: text
      fast: true
    - name: actor
      type: object
      field_mappings:
      - name: login
        fast: true
        type: text
    - name: payload
      type: object
      field_mappings:
      - name: description
        type: text
        tokenizer: default
      - name: pull_request
        type: object
        field_mappings:
        - name: head
          type: object
          field_mappings:
            - name: repo
              type: object
              field_mappings:
                - name: description
                  type: text
                  tokenizer: default
```

I would expect that we just ignore the `null` value and still index the document.
