### ISSUE TITLE
Explore whether we can support the Jaeger data source in Grafana without using Jaeger frontend as a proxy.

### ISSUE THREAD

**Issue by guilload** [quickwit-oss/quickwit#3711]
That's how you setup a proxy Jaeger data source:
```yaml
- id: 1
  name: Jaeger
  type: jaeger
  typeName: Jaeger
  access: proxy
  url: http://jaeger:16686
  isDefault: false
  jsonData:
    httpMethod: POST
  readOnly: false
```

The idea would be to point directly to Quickwit with `url: http://localhost:7280/jaeger`
