### ISSUE TITLE
Aggregations do not work on a field declared as fast with a parent field is a JSON field with `fast: false`

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#3896]
Minimal reproducible example:

```yaml
version: 0.6

index_id: test

doc_mapping:
  field_mappings:
    - name: timestamp
      type: datetime
    - name: raw_line
      type: json
      tokenizer: default
      fast: false
    - name: raw_line.statusCode
      type: u64
      fast: true

indexing_settings:
  commit_timeout_secs: 10
```

Ingest the document:

```json
{"timestamp": 1695934164, "raw_line": {"statusCode": 100, "body": "this is the body"}}
```

Then execute the term aggregation:

```json
{
  "query": "*",
  "aggs": {
     "my_term": {
        "terms": {
           "field": "raw_line.statusCode"
        }
     }
  }
}
```
