### ISSUE TITLE
Add kafka source example with several pipelines in the source configuration page

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#3923]
Just something like this will do the job

```yaml
version: 0.6
source_id: kafka-source
source_type: kafka
max_num_pipelines_per_indexer: 2
desired_num_pipelines: 3
params:
  topic: vpc-logs
  client_params:
    bootstrap.servers: broker-1:9092,broker-2:9092
```
