### ISSUE TITLE
about About Multiple Indexers with kafka source config

### ISSUE THREAD

**Issue by yangshike** [quickwit-oss/quickwit#3927]
hi，
I want to configure multiple indexers for the Kafka source, but I couldn't find multiple indexer configuration documents
I have a node that is started through quickwit run -- config config.yaml (which already includes an indexer, kafka source, and some other ingest indexing methods),

I would like to start a separate indexer service to connect to this cluster and only serve as the second indexer for Kafka source,

I tried to start the second node, but on the Kafka end, I saw that only one node was consuming data at the same time

**Comment by fmassot** [comment]
Hi @yangshike 

We indeed need a good example in our docs on this (cf #3923).

```yaml
version: 0.6
source_id: kafka-source
source_type: kafka
max_num_pipelines_per_indexer: 1
desired_num_pipelines: 4
params:
  topic: logs
  client_params:
    bootstrap.servers: broker-1:9092,broker-2:9092
```

See this [docs](https://quickwit.io/docs/configuration/source-config) page to have details about the source parameters.
