### ISSUE TITLE
Add a bench for QuickwitCollector and optimize it.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#3978]
There are a lot of performance headroom for QuickwitCollector. This is our hottest code, we should have benchmarks to help its iterating on it.

Ideally we probably want to bench over >1million worth of documents from gharchive. I think we can use the schema from 

```
version: 0.6
index_id: gh-archive
doc_mapping:
  field_mappings:
      - name: payload
        type: object
        field_mappings:
        - name: title
          type: text
        - name: body
          type: text
      - name: issue
        type: object
        field_mappings:
        - name: title
          type: text
        - name: body
          type: text
    - name: created_at
      type: datetime
      fast: true
      input_formats:
      - rfc3339
  timestamp_field: created_at
  mode: dynamic
```

This is probably something we don't want on the repo however.
Maybe we can have the data gzipped somewhere on the internet (s3? github?), and have a program that downloads the corpus and builds the split. (let's not make it part of the workspace)

Benchmarking at the tantivy level is ok.
