### ISSUE TITLE
Update the distributed search tutorial 

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#4004]
Improvements:

- use `enabled_services` parameters in the node configs
- (optional) add an alternative cURL command for search using docusaurus tabs

Example of searcher 1 config.

```yaml
version: 0.6
node_id: searcher-1
listen_address: 127.0.0.1
rest_listen_port: 7280
enabled_services:
  - metastore
  - control-plane
  - searcher
  - indexer
  - janitor

peer_seeds:
  - 127.0.0.1:7290 # searcher-2
  - 127.0.0.1:7300 # searcher-3

``` 

searcher 2

```yaml
version: 0.6
node_id: searcher-2
listen_address: 127.0.0.1
rest_listen_port: 7290
enabled_services:
  - searcher
peer_seeds:
  - 127.0.0.1:7280 # searcher-1
  - 127.0.0.1:7300 # searcher-3
```

```yaml
version: 0.6
node_id: searcher-3
listen_address: 127.0.0.1
rest_listen_port: 7300
enabled_services:
  - searcher
peer_seeds:
  - 127.0.0.1:7280 # searcher-1
  - 127.0.0.1:7290 # searcher-2

```
