### ISSUE TITLE
Complete the minio config storage with the URI of an index

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#4285]
The storage config page gives the following storage config for MinIO: 

```yaml
storage:
  s3:
    flavor: minio
    endpoint: http://127.0.0.1:9000
```

Good. Then, a user will have to define the `default_index_root_uri`. 

I saw at least two times users set `default_index_root_uri: s3://127.0.0.1:9000/indexes`, which is wrong.  The right value is `default_index_root_uri: s3://indexes`

We could at least give an example in the docs + link to the [minio tutorial](https://blog.min.io/minio-quickwit/). We could also check the config when starting quickwit and raise an error.
