### ISSUE TITLE
Allow GCS connection through the meta API.

### ISSUE THREAD

**Issue by fulmicoton** [quickwit-oss/quickwit#4371]
Right now we get an error if no credential path or env variable is given.

(It seems like reqsign supports loading token via the meta API)

**Comment by Xuanwo** [comment]
> Right now we get an error if no credential path or env variable is given.

OpenDAL (and reqsign) will try to load credential from `GOOGLE_APPLICATION_CREDENTIALS` and vm metadata while credential is not set. They should work by default.

Would you like to check if your VM has configued a service account?

**Comment by fulmicoton** [comment]
Right now the quickwit code fails if no env variable or no config key is configured. See #4373.

I tried to get it to work from GKE without success, but that's because the service account is not properly configured I believe.

**Comment by Xuanwo** [comment]
> Right now the quickwit code fails if no env variable or no config key is configured. See #4373.

Got it, thanks for the fix.

> I tried to get it to work from GKE without success, but that's because the service account is not properly configured I believe.

Please let me know it doesn't work. We have an integration test for this in reqsign:

```yaml
  test_gcs_web_identify:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    if: github.event_name == 'push' || !github.event.pull_request.head.repo.fork
    steps:
      - uses: actions/checkout@v4
      - name: Install cargo-nextest
        run: curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C ${CARGO_HOME:-~/.cargo}/bin

      - id: auth
        uses: google-github-actions/auth@v2.0.1
        with:
          token_format: "access_token"
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER_ID }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}

      - name: Test
        run: cargo nextest run --no-fail-fast
        env:
          RUST_LOG: DEBUG
          RUST_BACKTRACE: full
          REQSIGN_GOOGLE_CREDENTIAL_PATH: ${{steps.auth.outputs.credentials_file_path}}
```

WIF should work for google.
