### ISSUE TITLE
Dynamic mode indexes may have spaces in the names, but strict indexes can't

### ISSUE THREAD

**Issue by nickkaltner** [quickwit-oss/quickwit#4793]
**Describe the bug**

I try to create two indexes, one like

```yaml
version: 0.7
index_id: sales-schemaless
doc_mapping:
  mode: dynamic
indexing_settings:
  commit_timeout_secs: 30
```

and one like

```yaml
version: 0.7
index_id: sales-schema
doc_mapping:
  mode: strict
  timestamp_field: "Order Date"
  field_mappings:
    - name: Order Date
      type: datetime
      input_formats:
        - iso8601
      fast: true
    - name: "Ship Date"
      type: datetime
      input_formats:
        - iso8601
      fast: true
    - name: "Country"
      type: text
indexing_settings:
 commit_timeout_secs: 30
```

the second one won't create with the message;

```
./quickwit index create --index-config sales_schema_config.yaml
❯ Creating index...
✘ command failed: API error: (code=400 Bad Request, message=invalid config: failed to parse YAML file: field name `Order Date` contains illegal characters. field names must only contain uppercase and lowercase ASCII letters, digits, hyphens `-`, periods `.`, and underscores `_`)

Caused by:
    (code=400 Bad Request, message=invalid config: failed to parse YAML file: field name `Order Date` contains illegal characters. field names must only contain uppercase and lowercase ASCII letters, digits, hyphens `-`, periods `.`, and underscores `_`)
```

but the first one will create and actually work with a jsonl that has spaces in the keys! So i can't force a schema on a data set that works if the schema is dynamic. 

**Steps to reproduce (if applicable)**

1. create the schemas above 
2.insert the following data into the dynamic schema

```jsonl
{"Country":"Azerbaijan","Order Date":"2014-10-08T00:00:00+00:00","Ship Date":"2014-10-23T00:00:00+00:00"}
```

with the command

```
./quickwit tool local-ingest --index sales-schemaless --input-path
```

3. observe that it works :) 
4. try to create the second schema
5. observe it doesn't work

**Expected behavior**

I'd expect the strict schemas to be able to emulate the dynamic schemas

**Configuration:**
Please provide:

1. Output of `quickwit --version`

`Quickwit 0.8.0 (aarch64-unknown-linux-gnu 2024-03-18T15:20:23Z 7af4596)`

2. The index_config.yaml

see above^^^
