### ISSUE TITLE
Dynamic fields term set query not working

### ISSUE THREAD

**Issue by camerondavison** [quickwit-oss/quickwit#4945]
I am able to get
```
data.event_type:StandardMgaQuoteIssued OR data.event_type:QuoteIssued
```

query to work, but I cannot get a term set query to work, like
```
data.event_type:IN [StandardMgaQuoteIssued QuoteIssued]
```

This is my kafka ingestion configuration
```
version: 0.6
index_id: events

doc_mapping:
  field_mappings:
    - name: id
      type: text
      tokenizer: raw
...
    - name: data
      type: json
      tokenizer: default
    - name: occurred_at
      type: datetime
      fast: true
      input_formats:
        - rfc3339
        - "%Y-%m-%dT%H:%M:%S.%f"
      precision: seconds
  timestamp_field: occurred_at

indexing_settings:
  commit_timeout_secs: 10
```

```
{
  "build": {
    "build_date": "2024-03-29T16:35:13Z",
    "build_profile": "release",
    "build_target": "x86_64-unknown-linux-gnu",
    "cargo_pkg_version": "0.8.1",
    "commit_date": "2024-03-29T14:09:41Z",
    "commit_hash": "e6c53967f8e57401d93bcc555d361dad69bd4ece",
    "commit_short_hash": "e6c5396",
    "commit_tags": [
      "v0.8.1"
    ],
    "version": "v0.8.1"
  },
  "runtime": {
    "num_cpus_logical": 4,
    "num_cpus_physical": 2,
    "num_threads_blocking": 3,
    "num_threads_non_blocking": 1
  }
}
```

----
Im not sure if it may be a feature or a bug, based on the dynamic json fields that it is trying to use.
