### ISSUE TITLE
datetime fields' output_format : "unix_timestamp_nanos" returns incorrect (truncated) values

### ISSUE THREAD

**Issue by ddelemeny** [quickwit-oss/quickwit#5007]
**Describe the bug**
Timestamps with nanosecond precision can't currently be retrieved without precision loss. The `unix_timestamp_nanos` output format returns truncated values.

**Expected behavior**
A timestamp ingested with nanosecond precision should be serialized back to its ingest value in search results when using the output format `unix_timestamp_nanos`.

```
Quickwit 0.8.0 (x86_64-unknown-linux-gnu 2024-04-25T10:11:08Z 9de883d)
```

```
version: 0.7

index_id: otel-logs-v0_7-FASTNANO

doc_mapping:
  mode: dynamic
  field_mappings:
    - name: timestamp_nanos
      type: datetime
      input_formats: [unix_timestamp]
      output_format: unix_timestamp_nanos
      indexed: false
      fast: true
      fast_precision: nanoseconds
    - name: observed_timestamp_nanos
      type: datetime
      input_formats: [unix_timestamp]
      output_format: unix_timestamp_nanos
    - name: severity_text
      type: text
      tokenizer: raw
      fast: true
    - name: severity_number
      type: u64
      fast: true
    - name: body
      type: json
      tokenizer: default
    - name: attributes
      type: json
      tokenizer: raw
      fast: true

  timestamp_field: timestamp_nanos

indexing_settings:
  commit_timeout_secs: 10

search_settings:
  default_search_fields: [body.message]

```

Blocking for quickwit-oss/quickwit-datasource#118
