### ISSUE TITLE
Quickwit thinks its on ECS with pod identiy enabled in EKS

### ISSUE THREAD

**Issue by mzupan** [quickwit-oss/quickwit#5247]
**Describe the bug**
AWS/EKS now has pod identity addon for easier use of IAM roles inside EKS. 

https://docs.aws.amazon.com/eks/latest/userguide/pod-identities.html

With that enabled it seems quickwit thinks its in ECS and hitting the ECS metadata endpoint and not the ec2 one. 

This is a log 

```


quickwit-indexer-0 quickwit 2024-07-23T13:24:39.681Z  WARN index-doc-batches{index_id=logs source_id=_ingest-api-source pipeline_uid=01J3E542CEMSW5W81CHG1HV70W workbench_id=01J3FW61Z5HA9ZZY138GFBV27N}:uploader: quickwit_indexing::actors::uploader: Failed to upload split. Killing! cause=failed uploading key 01J3FW61ZGH09AAA0261CWG67P.split in bucket s3://company-quickwit-logs-dev/indexes/logs
quickwit-indexer-0 quickwit
quickwit-indexer-0 quickwit Caused by:
quickwit-indexer-0 quickwit     0: storage error(kind=Internal, source=failed to construct request: failed to load credentials from the credentials cache: the credentials provider was not properly configured: invalid full URI for ECS provider (URI did not refer to the loopback interface): http://169.254.170.23/v1/credentials (ConstructionFailure(ConstructionFailure { source: CredentialsStageError { source: InvalidConfiguration(InvalidConfiguration { source: "invalid full URI for ECS provider (URI did not refer to the loopback interface): http://169.254.170.23/v1/credentials" }) } })))
quickwit-indexer-0 quickwit     1: failed to construct request: failed to load credentials from the credentials cache: the credentials provider was not properly configured: invalid full URI for ECS provider (URI did not refer to the loopback interface): http://169.254.170.23/v1/credentials (ConstructionFailure(ConstructionFailure { source: CredentialsStageError { source: InvalidConfiguration(InvalidConfiguration { source: "invalid full URI for ECS provider (URI did not refer to the loopback interface): http://169.254.170.23/v1/credentials" }) } })) split_id="01J3FW61ZGH09AAA0261CWG67P"
quickwit-indexer-0 quickwit 2024-07-23T13:24:39.684Z ERROR quickwit_actors::spawn_builder: actor-failure cause=failed to receive command from uploader
```

Switching back to IRSA where you define a role annotation in the serviceaccount and resstarting indexer/seacher pods fixed the issue. 

I verified I was able to launch a pod using the quickwit serviceaccount and access the s3 bucket just fine from an alpine pod.

**Steps to reproduce (if applicable)**

1. enable pod itentiy addon and use it with quickwit
**Expected behavior**
quickwit works with s3

**Configuration:**
Please provide:

```
  fullnameOverride: quickwit

  indexer:
    replicaCount: 3

    resources:
      requests:
        cpu: 4
        memory: 6Gi
      limits:
        memory: 6Gi

    serviceAnnotations:
      service.kubernetes.io/topology-mode: auto
      service.kubernetes.io/topology-aware-hints: auto

  searcher:
    replicaCount: 3
    resources:
      requests:
        cpu: 2
        memory: 6Gi
      limits:
        memory: 6Gi

    serviceAnnotations:
      service.kubernetes.io/topology-mode: auto
      service.kubernetes.io/topology-aware-hints: auto

  metastore:
    replicaCount: 1

    extraEnv:
      POSTGRES_HOST: postgresql
      POSTGRES_DATABASE: quickwit
      POSTGRES_PORT: "5432"
      POSTGRES_USERNAME: quickwit

    extraEnvFrom:
      - secretRef:
          name: postgresql-quickwit

    resources:
      requests:
        cpu: 1
        memory: 3Gi
      limits:
        memory: 3Gi

  janitor:
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        memory: 1Gi

  #
  # this will create the indexes defined in the config.indexes section
  bootstrap:
    enabled: true

  config:
    default_index_root_uri: s3://company-quickwit-logs-dev/indexes

    storage:
      s3:
        region: us-east-1

    ingest_api:
      max_queue_memory_usage: 6GiB
      max_queue_disk_usage: 30GiB

  seed:
    indexes:
      - version: 0.8
        index_id: logs
        doc_mapping:
          mode: dynamic
          field_mappings:
            - name: timestamp
              type: datetime
              fast: true
              input_formats:
                - iso8601
              output_format: unix_timestamp_secs
            - name: message
              type: text
              tokenizer: default
              record: position
          timestamp_field: timestamp
        search_settings:
          default_search_fields: [message]
        retention:
          period: 30 days
          schedule: daily
        indexing_settings:
          merge_policy:
            type: limit_merge
            max_merge_ops: 3
            merge_factor: 10
            max_merge_factor: 12

  serviceMonitor:
    enabled: true


```
