### ISSUE TITLE
Flaky ES API sort test

### ISSUE THREAD

**Issue by rdettai** [quickwit-oss/quickwit#5373]
**Describe the bug**
The 0001-sort-elasticapi.yaml test suite fails often

The dataset is
```
  - {"count": 10, "id": 1}
  - {"count": 10, "id": 2}
  - {"count": 15, "id": 2}
  - {"id": 3}
  - {"count": 10, "id": 0}
  - {"count": -2.5, "id": 4}
  - {"id": 5}
  ```

The expected value is 
```
expected:
  hits:
    total:
      value: 4
      relation: "eq"
    hits:
      - _source: { "count": 15, "id": 2 }
      - _source: { "count": -2.5, "id": 4 }
      - _source: { "id": 5 }
      - _source: { "id": 3 }
 ```
But the id 3 sometimes appears before the id 5 in the response. I'm not sure why we expect this order in the first place.

**Steps to reproduce (if applicable)**
See CI runs such as https://github.com/quickwit-oss/quickwit/actions/runs/10628590537/job/29466183519

**Expected behavior**
Stable test
