### ISSUE TITLE
failed to fetch hotcache and footer from s3

### ISSUE THREAD

**Issue by EthanGeekFan** [quickwit-oss/quickwit#5386]
**Describe the bug**
Quickwit server can show the indexes page and everything works fine on checking the published splits, size of index, number of documents, etc. But when searching, returns 500 internal error:
```
Error: { "message": "internal error: `(internal error: `failed to fetch hotcache and footer from s3://my-bucket/quickwit_datastore for split `01J6Z8F0HQ2DAZMVGPRY1P59Z8``, split_id: 01J6Z8F0HQ2DAZMVGPRY1P59Z8), (internal error: `failed to fetch hotcache and footer from s3://my-bucket/quickwit_datastore for split `01J6Z8DZM767XX1MDET414KYT8``, split_id: 01J6Z8DZM767XX1MDET414KYT8), (internal error: `failed to fetch hotcache and footer from s3://my-bucket/quickwit_datastore for split `01J6Z8D5T7VY2NTPREZSJ87J8Y``, split_id: 01J6Z8D5T7VY2NTPREZSJ87J8Y)`" }
```
This error occurs for all splits. When I search for all documents with no date range, the error is very long, reporting same error on every split that exists.

However, another server that is running on another machine, using same s3, metastore and config, works correctly and search works.

I can confirm that the errored splits exists on s3 when I ls objects using aws cli tools. 

Thank you so much for helping!

**Steps to reproduce (if applicable)**

1. Start a server
2. Start another instance with same config on another machine and search on this instance's UI

**Expected behavior**
Both instance should search correctly.

**Configuration:**
Please provide:

Both instance on different machine are running official docker image quickwit:0.8.2

1. Output of `quickwit --version`
```
Quickwit 0.8.2 (x86_64-unknown-linux-gnu 2024-06-17T16:36:47Z 42766b8)
```
2. The index_config.yaml
```yaml
version: 0.8
index_id: my-index

retention:
  period: 90 days
  schedule: daily

index_uri: s3://my-bucket/quickwit_datastore

doc_mapping:
  # mode: lenient
  store_source: false
  timestamp_field: parse_timestamp
  field_mappings:
    ...
```
