### ISSUE TITLE
`regexp` query with space on `concatenate` field returns no results

### ISSUE THREAD

**Issue by tontinton** [quickwit-oss/quickwit#5714]
**The bug**
`regexp` query with space on `concatenate` field returns no results.

**Steps to reproduce**

1. Create index with concatenate field:
```yaml
version: 0.8
index_id: stackraw

doc_mapping:
  mode: dynamic
  dynamic_mapping:
    tokenizer: whitespace
    record: position
  field_mappings:
    - name: _raw
      type: concatenate
      include_dynamic_fields: true
      tokenizer: whitespace
      record: position
    - name: creationDate
      type: datetime
      fast: true
      input_formats:
        - rfc3339
      fast_precision: seconds
  timestamp_field: creationDate

search_settings:
  default_search_fields: [_raw]
indexing_settings:
  commit_timeout_secs: 10
```

2. Run `_elastic` query with `{"regexp": {"_raw": {"value": "hello .*rld"}}}` -> doesn't return logs that contain fields with "hello world".

What's funny is that without the space `{"regexp": {"_raw": {"value": "hell.*"}}}` does work, so it probably has something to do with terms.
