### ISSUE TITLE
Deploying quickwit on MinIO requires a region to be specified

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/quickwit#5822]
In the documentation, we give this configuration for MinIO;

```
storage:
  s3:
    flavor: minio
    endpoint: http://127.0.0.1:9000
```

But the s3 client fails to connect to MinIO and asks for a region. We should add a region in the config example.  A user set a fake value "us-east-1" and it worked. I'm wondering if a random value is accepted too.

```
storage:
  s3:
    flavor: minio
    region: us-east-1
    endpoint: http://127.0.0.1:9000
```
